apiVersion: apps/v1
kind: Deployment
metadata:
  name: cim-eindopdracht-deployment
  labels:
    app: cim-eindopdracht
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cim-eindopdracht
  template:
    metadata:
      labels:
        app: cim-eindopdracht
    spec:
      containers:
      - name: cim-eindopdracht
        image: ghcr.io/noudadrichem/cloud-infra-eindopracht:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cim-eindopdracht-svc
spec:
  selector:
    app: cim-eindopdracht
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
